# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0002_webuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebUser',
        ),
    ]
