# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0005_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='surname',
        ),
    ]
