# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0008_auto_20180606_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
