# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ykea', '0010_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='bought',
            field=models.IntegerField(default=0),
        ),
    ]
